// Frontend transaction type definitions
export type BaseTransaction = {
  id?: string; // Optional as it may be generated by backend
  amount: number;
  date: string; // Store as ISO string for API compatibility
  description?: string;
  user_id?: string; // Added to match backend expectation
};

export type ExpenseTransaction = BaseTransaction & {
  type: "expense";
  category: string;
  merchant: string;
  currency: string; // Added to match backend expectation
};

export type IncomeTransaction = BaseTransaction & {
  type: "income";
};

export type TransferTransaction = BaseTransaction & {
  type: "transfer";
  sender: string;
  receiver: string;
};

export type DepositTransaction = BaseTransaction & {
  type: "deposit";
};

export type TransactionModel =
  | ExpenseTransaction
  | IncomeTransaction
  | TransferTransaction
  | DepositTransaction;
